<?php

namespace Services;

/**
 * Test class for TicketService.
 * Generated by PHPUnit on 2011-08-23 at 22:53:20.
 */
class TicketServiceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @todo Implement testAddTicket().
     */
    public function testAddTicket()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
