<?php

namespace Test\Domain;

use Domain\Atm;

/**
 * Test class for Atm.
 * Generated by PHPUnit on 2011-07-28 at 19:21:23.
 */
class AtmTest extends \PHPUnit_Framework_TestCase
{
    public function testHasId()
    {
        $o_atm = new Atm('127.0.0.1', '1st floor');
        $this->assertAttributeEmpty('id', $o_atm);
    }

    public function testHasNetaddress()
    {
        $expected = '127.0.0.1';
        $o_atm = new Atm($expected, '1st floor');
        $this->assertAttributeEquals($expected, 'netaddress', $o_atm);
    }

    public function testHasPlace()
    {
        $expected = '1st floor';
        $o_atm = new Atm('127.0.0.1', $expected);
        $this->assertAttributeEquals($expected, 'place', $o_atm);
    }

}
