<?php

namespace Test\Domain;

use Domain\Coupon;

/**
 * Test class for Coupon.
 * Generated by PHPUnit on 2011-08-27 at 18:35:11.
 */
class CouponTest extends \PHPUnit_Framework_TestCase
{
    public function testHasId()
    {
        $o_coupon = new Coupon(new \DateTime(), 10);
        $this->assertAttributeEmpty('id', $o_coupon);
    }

    public function testHasStartDate()
    {
        $o_expected = new \DateTime('2011-01-01');

        $o_coupon = new Coupon($o_expected, '10');
        $this->assertAttributeEquals($o_expected, 'start_date', $o_coupon);
    }

    public function testHasNumber()
    {
        $s_expected = '10';

        $o_coupon = new Coupon(new \DateTime(), $s_expected);
        $this->assertAttributeEquals($s_expected, 'number', $o_coupon);
    }

    public function testHasEmptyNumber()
    {
        $this->setExpectedException('DomainException', 'Coupon number cannot be empty');

        $o_coupon = new Coupon(new \DateTime(), '');
        $this->assertAttributeEquals('', 'number', $o_coupon);
    }

}
