<?php

namespace Test\Domain;

use Domain\Room;

/**
 * Test class for Atm.
 * Generated by PHPUnit on 2011-07-28 at 19:21:23.
 */
class RoomTest extends \PHPUnit_Framework_TestCase
{
    public function testHasId()
    {
        $o_room = new Room('1', 'reg');
        $this->assertAttributeEmpty('id', $o_room);
    }

    public function testHasNumber()
    {
        $expected = '1';
        $o_room = new Room($expected, 'reg');
        $this->assertAttributeEquals($expected, 'number', $o_room);
    }

    public function testHasDescription()
    {
        $expected = 'reg';
        $o_room = new Room('1', $expected);
        $this->assertAttributeEquals($expected, 'description', $o_room);
    }

    public function testHasEmptyDescription()
    {
        $this->setExpectedException('DomainException', 'Room description cannot be empty');
        $o_room = new Room('1', '');
        $this->assertAttributeEquals('', 'description', $o_room);
    }

    public function testHasRecordTrue()
    {
        $o_room = new Room('1', 'reg');
        $this->assertAttributeEquals(true, 'record', $o_room);
    }

    public function testHasRecordFalse()
    {
        $o_room = new Room('1', 'reg', false);
        $this->assertAttributeEquals(false, 'record', $o_room);
    }

}
